title: "Cuaderno personal de estudio y reflexión"
description: "Reflexiones, medicina, filosofía y disciplina."
theme: minima
header_pages:
  - about.md
  - cuaderno.md
  - medicina.md
  - filosofia.md
  - fe-y-etica.md
  - proyectos-personales.md
